// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3MvKK0pRdGEfxrtstk50EjRCd1V16VU',
    appId: '1:1043831583248:web:25c16625356801a7fc5095',
    messagingSenderId: '1043831583248',
    projectId: 'emlak-saha',
    authDomain: 'emlak-saha.firebaseapp.com',
    storageBucket: 'emlak-saha.firebasestorage.app',
    measurementId: 'G-MK6XXLMDHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_R4oNWEb2zzl_Yr9ZW3rcHOS77fMp8g4',
    appId: '1:1043831583248:android:9f560a117c6f4204fc5095',
    messagingSenderId: '1043831583248',
    projectId: 'emlak-saha',
    storageBucket: 'emlak-saha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLHI-nPr32COPl1wtEbiKTAwUxQhi2UPY',
    appId: '1:1043831583248:ios:5a37edd4903a165dfc5095',
    messagingSenderId: '1043831583248',
    projectId: 'emlak-saha',
    storageBucket: 'emlak-saha.firebasestorage.app',
    iosBundleId: 'com.example.emlakSahaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLHI-nPr32COPl1wtEbiKTAwUxQhi2UPY',
    appId: '1:1043831583248:ios:5a37edd4903a165dfc5095',
    messagingSenderId: '1043831583248',
    projectId: 'emlak-saha',
    storageBucket: 'emlak-saha.firebasestorage.app',
    iosBundleId: 'com.example.emlakSahaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3MvKK0pRdGEfxrtstk50EjRCd1V16VU',
    appId: '1:1043831583248:web:f11681e51452806cfc5095',
    messagingSenderId: '1043831583248',
    projectId: 'emlak-saha',
    authDomain: 'emlak-saha.firebaseapp.com',
    storageBucket: 'emlak-saha.firebasestorage.app',
    measurementId: 'G-ENDJXZR3NF',
  );
}
